### ISSUE TITLE
paranext-multi-extension-template build error in main

### ISSUE THREAD

**Issue by irahopkinson** [paranext/paranext-core#1187]
**Describe the bug**
Building main in the `paranext-multi-extension-template` gives this error:
```sh
> paranext-multi-extension-template@0.0.1 build:main
> webpack --config ./webpack/webpack.config.main.ts

[webpack-cli] ValidationError: Invalid options object. Copy Plugin has been initialized using an options object that does not match the API schema.
 - options.patterns should be a non-empty array.
    at validate (C:\Users\Ira\src\paranext-multi-extension-template\node_modules\schema-utils\dist\validate.js:158:11)
    at new CopyPlugin (C:\Users\Ira\src\paranext-multi-extension-template\node_modules\copy-webpack-plugin\dist\index.js:171:5)
    at configMain (C:\Users\Ira\src\paranext-multi-extension-template\webpack\webpack.config.main.ts:51:7)
    at async loadConfigByPath (C:\Users\Ira\src\paranext-multi-extension-template\node_modules\webpack-cli\lib\webpack-cli.js:1445:31)
    at async Promise.all (index 0)
    at async WebpackCLI.loadConfig (C:\Users\Ira\src\paranext-multi-extension-template\node_modules\webpack-cli\lib\webpack-cli.js:1460:35)
    at async WebpackCLI.createCompiler (C:\Users\Ira\src\paranext-multi-extension-template\node_modules\webpack-cli\lib\webpack-cli.js:1781:22)
    at async WebpackCLI.runWebpack (C:\Users\Ira\src\paranext-multi-extension-template\node_modules\webpack-cli\lib\webpack-cli.js:1877:20)
    at async Command.<anonymous> (C:\Users\Ira\src\paranext-multi-extension-template\node_modules\webpack-cli\lib\webpack-cli.js:944:21)
    at async Command.parseAsync (C:\Users\Ira\src\paranext-multi-extension-template\node_modules\webpack-cli\node_modules\commander\lib\command.js:935:5) {
  errors: [
    {
      instancePath: '/patterns',
      schemaPath: '#/properties/patterns/minItems',
      keyword: 'minItems',
      params: [Object],
      message: 'must NOT have fewer than 1 items',
      schema: 1,
      parentSchema: [Object],
      data: []
    }
  ],
  schema: {
    definitions: { ObjectPattern: [Object], StringPattern: [Object] },
    type: 'object',
    additionalProperties: false,
    properties: { patterns: [Object], options: [Object] },
    required: [ 'patterns' ]
  },
  headerName: 'Copy Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
```

**To Reproduce**

1. Clone https://github.com/paranext/paranext-multi-extension-template
2. Run `npm i`
3. Run `npm run build:main`
4. See the above error

**Expected behavior**
The build should finish without error.

**Comment by tjcouch-sil** [comment]
There's nothing to build in the multi template since there are no extensions to build. Is this suggesting we adjust the scripts to add some output to say something along these lines?

**Comment by irahopkinson** [comment]
I wasn't thinking too deeply about this. I just wanted to document it since I was in the middle of updating dependencies. I had run the same command on the `paranext-extension-template` which of course ran fine after dependency updates. I was just doing the same here as a check, but you are right, there is nothing to build. However, I would still expect it to run without error, what do you think? Or do we just close this as expected?

**Comment by tjcouch-sil** [comment]
Good idea :) Fixed in https://github.com/paranext/paranext-multi-extension-template/pull/27

![image](https://github.com/user-attachments/assets/f38d5e51-4f45-4cfc-9f39-8c2ffc6a2c79)

**Comment by irahopkinson** [comment]
I don't know what I'm doing wrong, but I still get the same error on the `tailwind` branch (note I'm running `npm run build:main` as per this issue description). (Also note I did an `npm i` first and it updated the `package-lock.json` file.)

**Comment by tjcouch-sil** [comment]
Oops; I didn't realize you were running `build:main`. I moved the instruction printout so it shows on all the build scripts.

**Comment by irahopkinson** [comment]
Note that `build:web-view` is running fine without errors so it doesn’t
need the message.

Blessings, Ira

----------------------------

Ira J Hopkinson

Programmer, Bible Translation Software

SIL Global <http://www.sil.org>  |  Paratext <https://paratext.org/> |
 Scripture
Forge <https://scriptureforge.org/>

**Comment by tjcouch-sil** [comment]
I applied it to `build:web-view` because it is meaningless to run that without an extension anyway. Might as well print the helpful instructions. :)

Fixed in https://github.com/paranext/paranext-multi-extension-template/pull/27

**Comment by tjcouch-sil** [comment]
Temporarily reopening til I get the multi-template bug fixed

**Comment by roopa0222** [comment]
Verified the fix: using `npm run build`  , `npm run build:main`  and `npm run build:web-view`

All 3 commands printed below message and did not throw any errors

`No extensions found! Please run `npm run create-extension -- <extension_name>` to create an extension. See README.md for more information.`

[BuildScriptsMessagesOnMultiExtension.txt](https://github.com/user-attachments/files/17383630/BuildScriptsMessagesOnMultiExtension.txt)
